<?php

namespace Netipar\SimplePay\Enums;

enum ErrorCode: int
{
    case GeneralError = 999;
    case InternalError = 1529;
    case InvalidPassword = 2003;
    case GeneralError2 = 2004;
    case MerchantNotFound = 2006;
    case InvalidEmail = 2008;
    case InvalidTransactionId = 2010;
    case InsufficientFunds = 2013;
    case PasswordRequired = 2014;
    case PaymentCancelledByUser = 2016;
    case AcquirerTimeout = 2019;
    case AcquirerError = 2020;
    case Interactive3dsRequired = 2021;
    case Repeated3dsFailed = 2023;
    case CardNotDeletableOrInvalidAmount = 2030;
    case InvalidCurrency = 2040;
    case CardInactive = 2063;
    case InvalidCardData = 2064;
    case CardNotChargeableOrLimitExceeded = 2066;
    case CardDataErrorOrNotExist = 2068;
    case InvalidCardDataOrNotExist = 2071;
    case InvalidCardDataCheckRequired = 2072;
    case InvalidCardDataCheckRequired2 = 2073;
    case CardholderNameTooLong = 2074;
    case InvalidCvc = 2077;
    case GeneralCardError = 2078;
    case AcquirerNotAvailable = 2079;
    case InvalidInputCode = 2130;
    case InvalidAddress = 2131;
    case InvalidBirthDate = 2132;
    case InternalError2 = 2999;
    case General3dsError = 3000;
    case Invalid3dsResponse = 3001;
    case ThreeDsProcessError = 3002;
    case ThreeDsProcessError2 = 3003;
    case ThreeDsChallengeRedirect = 3004;
    case ThreeDsInteractiveAuthRequired = 3005;
    case ThreeDsCardAssociationTimeout = 3006;
    case ThreeDsNotCapableCard = 3012;
    case ThreeDsProcessError3 = 3013;
    case Invalid3dsVersion = 3102;
    case ThreeDsDataFormatError = 3203;
    case ThreeDsInternalError = 3303;
    case ThreeDsVerificationTimeout = 3402;
    case ThreeDsTemporaryError = 3403;
    case ThreeDsPermanentError = 3404;
    case ThreeDsAcsCancelledByUser = 3501;
    case ThreeDsAcsTimeout = 3504;
    case ThreeDsAcsNoResponse = 3505;
    case ThreeDsAcsTransactionError = 3506;
    case ThreeDsAcsUnknownError = 3507;
    case ThreeDsAcsComponentError = 3508;
    case ApiGeneralError = 5000;
    case MerchantAccountNotFound = 5010;
    case TransactionNotFound = 5011;
    case MerchantAccountMismatch = 5012;
    case TransactionAlreadyExists = 5013;
    case InvalidTransactionType = 5014;
    case TransactionInPayment = 5015;
    case TransactionTimeout = 5016;
    case TransactionAborted = 5017;
    case TransactionAlreadyPaid = 5018;
    case InvalidTransactionIdentifier = 5019;
    case OriginalTotalCheckFailed = 5020;
    case TransactionAlreadyFinished = 5021;
    case TransactionInvalidState = 5022;
    case UnknownCurrency = 5023;
    case InvalidEmailAddress = 5024;
    case InvalidName = 5025;
    case TransactionBlockedByFraud = 5026;
    case TransactionLockError = 5027;
    case TransactionNotReconciled = 5028;
    case TransactionNotRefunded = 5029;
    case OperationNotAllowed = 5030;
    case RefundCancelNotAllowed = 5033;
    case StoredCardNotFound = 5040;
    case StoredCardExpired = 5041;
    case StoredCardDeactivated = 5042;
    case PhantomStoredCard = 5043;
    case RecurringNotEnabled = 5044;
    case RecurringRemoteIdRequired = 5045;
    case RecurringIdtsRequired = 5046;
    case RecurringDuplicateIdts = 5047;
    case RecurringUntilRequired = 5048;
    case RecurringUntilMismatch = 5049;
    case InvalidPaymentMethod = 5050;
    case InvalidReferenceNumber = 5051;
    case InvalidExternalReference = 5052;
    case InvalidTimestamp = 5053;
    case InvalidBillingFirstName = 5054;
    case InvalidBillingLastName = 5055;
    case InvalidBillingEmail = 5056;
    case InvalidBillingPhone = 5057;
    case InvalidBillingAddress = 5058;
    case InvalidBillingCity = 5059;
    case InvalidShippingFirstName = 5060;
    case InvalidShippingLastName = 5061;
    case InvalidShippingPhone = 5062;
    case InvalidShippingAddress = 5063;
    case InvalidShippingCity = 5064;
    case InvalidAmount = 5065;
    case InvalidCurrencyCode = 5066;
    case MissingBillingEmail = 5067;
    case InvalidShippingEmail = 5068;
    case MaxAmountExceeded = 5069;
    case DirectPaymentCreationError = 5070;
    case StoredCardInvalidLength = 5071;
    case StoredCardInvalidOperation = 5072;
    case OriginalIdMismatchOnRecurring = 5080;
    case RecurringTokenNotFound = 5081;
    case RecurringTokenInUse = 5082;
    case TokenTimesRequired = 5083;
    case TokenTimesTooLarge = 5084;
    case TokenUntilRequired = 5085;
    case TokenUntilTooLarge = 5086;
    case TokenMaxAmountRequired = 5087;
    case TokenMaxAmountTooLarge = 5088;
    case RecurringAndOneclickConflict = 5089;
    case RecurringTokenRequired = 5090;
    case RecurringTokenInactive = 5091;
    case RecurringTokenExpired = 5092;
    case RecurringAccountMismatch = 5093;
    case InvalidTimeoutDefinition = 5094;
    case PreselectedMethodRequired = 5095;
    case EamNotEnabled = 5096;
    case InvalidEamType = 5097;
    case InvalidSignature = 5100;
    case MissingOrderRef = 5101;
    case MissingOrderAmount = 5102;
    case MissingOrderCurrency = 5103;
    case MissingDate = 5104;
    case ConfirmationError = 5105;
    case InvalidRefundAmount = 5106;
    case InvalidRefundTotal = 5110;
    case OrderRefOrTransactionIdRequired = 5111;
    case SdkVersionRequired = 5113;
    case MissingIosMerchantId = 5150;
    case MissingExternalReference = 5151;
    case InvalidCardDetails = 5199;
    case InvalidInvoice = 5200;
    case MissingMerchantId = 5201;
    case AccessDenied = 5202;
    case InvalidData = 5203;
    case InvalidProductCode = 5204;
    case InvalidProductName = 5205;
    case InvalidProductInfo = 5206;
    case InvalidProductPrice = 5207;
    case InvalidVatValue = 5208;
    case InvalidQuantity = 5209;
    case InvalidProductVariant = 5210;
    case InvalidProductGroup = 5211;
    case InvalidPrice = 5212;
    case MissingOrderRefField = 5213;
    case InvalidDate = 5214;
    case InvalidDiscount = 5215;
    case InvalidShippingAmount = 5216;
    case InvalidMethod = 5217;
    case InvalidRedirectUrl = 5218;
    case MissingOrInvalidCustomerEmail = 5219;
    case InvalidLanguage = 5220;
    case InvalidDiscountFormat = 5221;
    case InvalidShippingFormat = 5222;
    case InvalidOrMissingCurrency = 5223;
    case InvalidTimeLimit = 5224;
    case InvalidWireTransferTimeLimit = 5225;
    case InvalidCommunicationState = 5226;
    case InvalidTimeoutSpec = 5227;
    case RefundLimitExceeded = 5228;
    case RefundDeadlineExpired = 5229;
    case RefundNotAllowed = 5230;
    case UserRedirectRequired = 5301;
    case InvalidRequestSignature = 5302;
    case InvalidRequestSignature2 = 5303;
    case TimeoutFailedCall = 5304;
    case FailedTransactionSend = 5305;
    case FailedTransactionCreation = 5306;
    case CurrencyMismatch = 5307;
    case TwoStepNotEnabled = 5308;
    case MissingInvoiceName = 5309;
    case MissingInvoiceCity = 5310;
    case MissingInvoiceZip = 5311;
    case MissingInvoiceAddress = 5312;
    case MissingItemTitle = 5313;
    case MissingItemPrice = 5314;
    case MissingItemQuantity = 5315;
    case MissingShippingName = 5316;
    case MissingShippingCity = 5317;
    case MissingShippingZip = 5318;
    case MissingShippingAddress = 5319;
    case MissingSdkVersion = 5320;
    case InvalidJsonFormat = 5321;
    case InvalidCountry = 5322;
    case InvalidFinishAmount = 5323;
    case ItemsOrTotalRequired = 5324;
    case InvalidUrl = 5325;
    case MissingCardId = 5326;
    case MaxOrderRefsExceeded = 5327;
    case MaxTransactionIdsExceeded = 5328;
    case QueryFromAfterUntil = 5329;
    case QueryFromAndUntilRequired = 5330;
    case InvalidTransactionSource = 5331;
    case TransactionIdAndTargetRequired = 5332;
    case MissingTransactionId = 5333;
    case CardDataRequired = 5334;
    case CardBinRequired = 5335;
    case AntiFraudHashRequired = 5336;
    case DataSerializationError = 5337;
    case AcquirerTransactionIdRequired = 5338;
    case QueryDateOrIdsRequired = 5339;
    case TransactionNotWalletBound = 5340;
    case PartnerOptionRequired = 5341;
    case PartnerAccountsRequired = 5342;
    case InvalidTransactionStatus = 5343;
    case InvalidTransactionStatus2 = 5344;
    case VatAmountBelowZero = 5345;
    case InvalidTransactionMode = 5346;
    case InvalidInstallmentPlan = 5347;
    case JwtRequired = 5348;
    case TransactionNotAllowedOnAccount = 5349;
    case InvalidEmailFormat = 5350;
    case InvalidDay = 5351;
    case SimpleBusinessAccountError = 5352;
    case InvalidStartEndParams = 5353;
    case InvalidDeviceId = 5354;
    case NotSoftPosAccount = 5355;
    case InvalidTemplate = 5356;
    case InvalidOrderRefFormat = 5357;
    case InvalidPeriod = 5358;
    case SoftPosNotAvailable = 5359;
    case RemoteAssignmentFailed = 5360;
    case RemoteDeletionFailed = 5361;
    case RemoteExpirationFailed = 5362;
    case OriginalTransactionRequired = 5363;
    case InvalidAdditionalInfo = 5364;
    case PartnerIdRequired = 5365;
    case InvalidEamStatus = 5366;
    case PaymentReferenceRequired = 5367;
    case DebtorBicRequired = 5368;
    case EndToEndIdRequired = 5369;
    case InvalidItemPrice = 5370;
    case InvalidItemQuantity = 5371;
    case AmountPaidToMerchant = 5372;
    case ApplePayNotEnabled = 5373;
    case EmailParamsRequired = 5380;
    case EmailTypeRequired = 5381;
    case CustomerEmailRequired = 5382;
    case InvalidSaltLength = 5401;
    case TransactionBaseRequired = 5402;
    case SimpleTransactionInPayment = 5403;
    case InvalidTransactionState = 5404;
    case TransactionNotInCdeSession = 5405;
    case WireTransactionCreated = 5413;
    case BrowserAcceptRequired = 5501;
    case BrowserAgentRequired = 5502;
    case BrowserIpRequired = 5503;
    case BrowserJavaRequired = 5504;
    case BrowserLanguageRequired = 5505;
    case BrowserColorRequired = 5506;
    case BrowserHeightRequired = 5507;
    case BrowserWidthRequired = 5508;
    case BrowserTzRequired = 5509;
    case InvalidType = 5530;
    case RavenCallError = 5555;
    case InvalidIdentificationCode = 5601;
    case InvalidMessage = 5602;
    case InvalidTransactionSituation = 5603;
    case InvalidRetailData = 5604;
    case InvalidDevice = 5605;
    case InvalidAccountId = 5606;
    case InvalidCustomerData = 5607;
    case InvalidVerificationCode = 5608;
    case MissingAuthCommunication = 5700;
    case RecommendationAlreadySent = 5701;
    case MissingInstallmentData = 5702;
    case InvalidOptionIndex = 5703;
    case DomainSelectionNotAvailable = 5704;
    case FullAmountPaymentNotAvailable = 5705;
    case AcquiringCallError = 5706;
    case InstallmentDataParseError = 5707;
    case InvalidInstallmentNumber = 5708;
    case MissingInstallmentOption = 5709;
    case MissingRecommendationCommunication = 5710;
    case SettlementAccountIdRequired = 5711;
    case SeriesSizeRequired = 5712;
    case InvalidCardType = 5812;
    case CardTransactionRejected = 5813;
    case ApiV1Disabled = 5814;
    case InvalidAppPlatform = 5900;
    case InvalidTimestampApp = 5901;
    case MobileAppNotFound = 5902;
    case DeeplinkDataNotFound = 5903;
    case PlatformOrInternalIdsRequired = 5904;
    case ReturnUrlsRequired = 5905;
    case MultipleReturnUrls = 5906;
    case RtpNotEnabled = 6100;
    case RtpInvalidBatchRef = 6101;
    case RtpInvalidOrderRef = 6102;
    case RtpInvalidTotal = 6103;
    case RtpInvalidCurrency = 6104;
    case RtpCustomerRequired = 6105;
    case RtpEmailOrAccountRequired = 6106;
    case RtpInvalidEmail = 6107;
    case RtpInvalidAccountNumber = 6108;
    case RtpInvalidRecurringTimes = 6109;
    case RtpRecurringUntilRequired = 6110;
    case RtpRecurringUntilExceeded = 6111;
    case RtpInvalidRecurringDay = 6112;
    case RtpInvalidRecurringInterval = 6113;
    case RtpEmptyPayments = 6114;
    case RtpInvalidPaymentResult = 6115;
    case RtpInvalidMerchant = 6116;
    case RtpSdkVersionRequired = 6117;
    case RtpTransactionAlreadyExists = 6118;
    case RtpInvalidLanguage = 6119;
    case RtpInvalidTransactionState = 6120;
    case RtpInvalidBatchOrOrderRef = 6121;
    case RtpInvalidQueryParams = 6122;
    case RtpOrderIdSizeExceeded = 6123;
    case RtpFromAfterUntil = 6124;
    case RtpFromAndUntilRequired = 6125;
    case RtpMissingRtpId = 6126;
    case RtpInvalidState = 6127;
    case RtpInvalidDeadline = 6128;
    case RtpOrderRefOrTransactionIdRequired = 6129;
    case RtpGiroError = 6130;
    case RtpTransactionNotFound = 6131;
    case RtpCustomerOrAccountRequired = 6132;
    case RtpCommentTooLong = 6133;
    case RtpAccountAlreadySet = 6134;
    case RtpTransactionCountExceeded = 6135;
    case RtpEmptyPaymentAmount = 6136;
    case RtpTransactionInit = 6140;
    case RtpWaitingForAccountData = 6141;
    case RtpReadyToSend = 6142;
    case RtpTransactionSent = 6143;
    case RtpTransactionReceived = 6144;
    case RtpTransactionAccepted = 6145;
    case RtpTransactionRejected = 6146;
    case RtpTransactionExpired = 6147;
    case RtpTransactionReversed = 6148;
    case RtpTransactionFailed = 6149;
    case RtpTransactionImmutable = 6150;
    case RtpTransactionPaid = 6151;
    case RtpTransactionNotFound2 = 6153;
    case RtpTransactionFinalState = 6154;
    case RtpInvalidPartnerAccount = 6155;
    case RtpReversalInProgress = 6156;
    case RtpTransactionsRequired = 6157;
    case RtpGeneralError = 6999;
    case SettlementMerchantNotFound = 7100;
    case SettlementGeneralError = 7999;

    public function description(): string
    {
        return match ($this) {
            self::GeneralError => 'Általános hibakód',
            self::InternalError => 'SimplePay belső hiba',
            self::InvalidPassword => 'Megadott jelszó érvénytelen',
            self::GeneralError2 => 'Általános hibakód',
            self::MerchantNotFound => 'Megadott kereskedő nem található',
            self::InvalidEmail => 'Megadott e-mail nem megfelelő',
            self::InvalidTransactionId => 'Megadott tranzakcióazonosító nem megfelelő',
            self::InsufficientFunds => 'Nincs elég fedezet a kártyán',
            self::PasswordRequired => 'Fizetéshez jelszó szükséges',
            self::PaymentCancelledByUser => 'A felhasználó megszakította a fizetést',
            self::AcquirerTimeout => 'Időtúllépés az elfogadói kommunikációban',
            self::AcquirerError => 'Elfogadó bank oldali hiba',
            self::Interactive3dsRequired => 'Kártyakibocsátó interaktív 3DS ellenőrzést igényel',
            self::Repeated3dsFailed => 'A megismételt 3DS ellenőrzés is sikertelen',
            self::CardNotDeletableOrInvalidAmount => 'Kártya nem törölhető, mert egyenlege pozitív / Megadott összeg helytelen',
            self::InvalidCurrency => 'Érvénytelen devizanem',
            self::CardInactive => 'Kártya inaktív',
            self::InvalidCardData => 'Hibás bankkártya adatok',
            self::CardNotChargeableOrLimitExceeded => 'Kártya nem terhelhető / limittúllépés miatt',
            self::CardDataErrorOrNotExist => 'Kártya adat hiba / nem létező kártya',
            self::InvalidCardDataOrNotExist => 'Hibás bankkártya adatok / nem létező kártya',
            self::InvalidCardDataCheckRequired => 'Hibásan megadott bankkártya adatok, ellenőrzés szükséges',
            self::InvalidCardDataCheckRequired2 => 'Hibásan megadott bankkártya adatok, ellenőrzés szükséges',
            self::CardholderNameTooLong => 'Kártyabirtokos neve több, mint 32 karakter',
            self::InvalidCvc => 'Érvénytelen CVC',
            self::GeneralCardError => 'Általános hiba, a kártyakibocsátó bank nem adja meg a hiba okát',
            self::AcquirerNotAvailable => 'A routingnak megfelelő elfogadó bank nem érhető el',
            self::InvalidInputCode => 'Helytelen bemeneti kód',
            self::InvalidAddress => 'Helytelen cím megadás',
            self::InvalidBirthDate => 'Helytelen születési dátum',
            self::InternalError2 => 'SimplePay belső hiba',
            self::General3dsError => 'Általános 3DS hiba',
            self::Invalid3dsResponse => 'Érvénytelen 3DS válaszüzenet',
            self::ThreeDsProcessError => '3DS folyamat hiba',
            self::ThreeDsProcessError2 => '3DS folyamat hiba',
            self::ThreeDsChallengeRedirect => 'Redirect 3DS challenge folyamán',
            self::ThreeDsInteractiveAuthRequired => '3DS interaktív azonosítás szükséges',
            self::ThreeDsCardAssociationTimeout => '3DS folyamat hiba - Kártyatársasági válasz nem, vagy késve érkezik meg',
            self::ThreeDsNotCapableCard => '3DS folyamat hiba, nem 3DS képes kártya',
            self::ThreeDsProcessError3 => '3DS folyamat hiba',
            self::Invalid3dsVersion => 'Érvénytelen 3DS verzió',
            self::ThreeDsDataFormatError => '3DS adat formátum hiba, vagy szükséges adat hiánya',
            self::ThreeDsInternalError => '3DS belső hiba, érvénytelen 3DS végpont',
            self::ThreeDsVerificationTimeout => '3DS ellenőrzési folyamat időtúllépés',
            self::ThreeDsTemporaryError => '3DS átmeneti rendszerhiba',
            self::ThreeDsPermanentError => '3DS tartósan fennálló rendszerhiba',
            self::ThreeDsAcsCancelledByUser => '3DS ACS - a felhasználó megszakította az interaktív azonosítást',
            self::ThreeDsAcsTimeout => '3DS ACS timeout, kártyakibocsátó bank oldal',
            self::ThreeDsAcsNoResponse => '3DS ACS timeout, kártyakibocsátó bank oldalról nem érkezik válasz',
            self::ThreeDsAcsTransactionError => '3DS ACS tranzakció hiba, kártyakibocsátó bank oldali',
            self::ThreeDsAcsUnknownError => '3DS ACS ismeretlen hiba, kártyakibocsátó bank oldal',
            self::ThreeDsAcsComponentError => '3DS ACS tranzakció hiba, kártyakibocsátó bank oldali komponensben',
            self::ApiGeneralError => 'Általános hibakód',
            self::MerchantAccountNotFound => 'A kereskedői fiók nem található',
            self::TransactionNotFound => 'A tranzakció nem található',
            self::MerchantAccountMismatch => 'A kereskedői fiók nem egyezik meg',
            self::TransactionAlreadyExists => 'A tranzakció már létezik',
            self::InvalidTransactionType => 'A tranzakció nem megfelelő típusú',
            self::TransactionInPayment => 'A tranzakció éppen fizetés alatt',
            self::TransactionTimeout => 'Tranzakció időtúllépés',
            self::TransactionAborted => 'A tranzakció meg lett szakítva',
            self::TransactionAlreadyPaid => 'A tranzakció már kifizetésre került',
            self::InvalidTransactionIdentifier => 'Érvénytelen tranzakcióazonosító',
            self::OriginalTotalCheckFailed => 'Az eredeti tranzakcióösszeg ellenőrzése sikertelen',
            self::TransactionAlreadyFinished => 'A tranzakció már lezárásra került',
            self::TransactionInvalidState => 'A tranzakció nem a kéréshez elvárt állapotban van',
            self::UnknownCurrency => 'Ismeretlen / nem megfelelő fiók devizanem',
            self::InvalidEmailAddress => 'Érvénytelen e-mail cím',
            self::InvalidName => 'Érvénytelen név',
            self::TransactionBlockedByFraud => 'Tranzakció letiltva (sikertelen fraud-vizsgálat)',
            self::TransactionLockError => 'Tranzakció zárolási probléma',
            self::TransactionNotReconciled => 'A tranzakció nem egyeztetett',
            self::TransactionNotRefunded => 'A tranzakció még nem került visszatérítésre',
            self::OperationNotAllowed => 'A művelet nem engedélyezett',
            self::RefundCancelNotAllowed => 'Visszatérítési tranzakció törlése nem engedélyezett',
            self::StoredCardNotFound => 'Tárolt kártya nem található',
            self::StoredCardExpired => 'Tárolt kártya lejárt',
            self::StoredCardDeactivated => 'Tárolt kártya inaktiválva',
            self::PhantomStoredCard => 'Fantom tárolt kártya',
            self::RecurringNotEnabled => 'Recurring nincs engedélyezve',
            self::RecurringRemoteIdRequired => 'Ismétlődő regisztrációhoz távoli azonosító szükséges',
            self::RecurringIdtsRequired => 'Ismétlődő regisztrációhoz IDTS szükséges',
            self::RecurringDuplicateIdts => 'Ismétlődő IDTS',
            self::RecurringUntilRequired => 'Recurring until szükséges',
            self::RecurringUntilMismatch => 'Recurring until eltér',
            self::InvalidPaymentMethod => 'Érvénytelen fizetési módszer',
            self::InvalidReferenceNumber => 'Érvénytelen referencia szám',
            self::InvalidExternalReference => 'Érvénytelen külső referencia',
            self::InvalidTimestamp => 'Érvénytelen időbélyeg',
            self::InvalidBillingFirstName => 'Érvénytelen számlázási keresztnév',
            self::InvalidBillingLastName => 'Érvénytelen számlázási vezetéknév',
            self::InvalidBillingEmail => 'Érvénytelen számlázási e-mail cím',
            self::InvalidBillingPhone => 'Érvénytelen számlázási telefonszám',
            self::InvalidBillingAddress => 'Érvénytelen számlázási cím',
            self::InvalidBillingCity => 'Érvénytelen számlázási város',
            self::InvalidShippingFirstName => 'Érvénytelen szállítási keresztnév',
            self::InvalidShippingLastName => 'Érvénytelen szállítási vezetéknév',
            self::InvalidShippingPhone => 'Érvénytelen szállítási telefonszám',
            self::InvalidShippingAddress => 'Érvénytelen szállítási cím',
            self::InvalidShippingCity => 'Érvénytelen szállítási város',
            self::InvalidAmount => 'Érvénytelen összeg',
            self::InvalidCurrencyCode => 'Érvénytelen pénznem',
            self::MissingBillingEmail => 'Kötelező számlázási e-mail cím hiányzik',
            self::InvalidShippingEmail => 'Érvénytelen szállítási e-mail cím',
            self::MaxAmountExceeded => 'Elérte a maximálisan megengedett összeget',
            self::DirectPaymentCreationError => 'Hiba az új közvetlen fizetés létrehozásakor',
            self::StoredCardInvalidLength => 'Tárolt kártya érvénytelen hossz',
            self::StoredCardInvalidOperation => 'Tárolt kártya érvénytelen művelet',
            self::OriginalIdMismatchOnRecurring => 'Eredeti azonosító eltérés az ismétlődő regisztrációnál',
            self::RecurringTokenNotFound => 'Recurring token nem található',
            self::RecurringTokenInUse => 'Recurring token használatban',
            self::TokenTimesRequired => 'Token times szükséges',
            self::TokenTimesTooLarge => 'Token times túl nagy',
            self::TokenUntilRequired => 'Token until szükséges',
            self::TokenUntilTooLarge => 'Token until túl nagy',
            self::TokenMaxAmountRequired => 'Token maxAmount szükséges',
            self::TokenMaxAmountTooLarge => 'Token maxAmount túl nagy',
            self::RecurringAndOneclickConflict => 'Recurring és oneclick regisztráció egyszerre nem indítható',
            self::RecurringTokenRequired => 'Recurring token szükséges',
            self::RecurringTokenInactive => 'Recurring token inaktív',
            self::RecurringTokenExpired => 'Recurring token lejárt',
            self::RecurringAccountMismatch => 'Recurring account eltérés',
            self::InvalidTimeoutDefinition => 'Érvénytelen időtúllépés meghatározás',
            self::PreselectedMethodRequired => 'Előre kiválasztott fizetési mód szükséges',
            self::EamNotEnabled => 'Az EAM használata nem engedélyezett',
            self::InvalidEamType => 'Érvénytelen EAM típus',
            self::InvalidSignature => 'Érvénytelen aláírás',
            self::MissingOrderRef => 'Hiányzó rendelési hivatkozás',
            self::MissingOrderAmount => 'Hiányzó rendelési összeg',
            self::MissingOrderCurrency => 'Hiányzó rendelési pénznem',
            self::MissingDate => 'Hiányzó dátum',
            self::ConfirmationError => 'Hiba a megerősítés során',
            self::InvalidRefundAmount => 'Érvénytelen visszatérítési összeg',
            self::InvalidRefundTotal => 'Nem megfelelő visszatérítendő összeg',
            self::OrderRefOrTransactionIdRequired => 'Az orderRef és a transactionId közül az egyik küldése kötelező',
            self::SdkVersionRequired => 'Az sdkVersion kötelező',
            self::MissingIosMerchantId => 'Hiányzó iOS kereskedő azonosító',
            self::MissingExternalReference => 'Hiányzó külső referencia',
            self::InvalidCardDetails => 'Érvénytelen kártyaadatok',
            self::InvalidInvoice => 'Érvénytelen számla',
            self::MissingMerchantId => 'A kereskedői fiók azonosítója hiányzik',
            self::AccessDenied => 'Hozzáférés megtagadva',
            self::InvalidData => 'Érvénytelen adat',
            self::InvalidProductCode => 'Érvénytelen termékkód',
            self::InvalidProductName => 'Érvénytelen terméknév',
            self::InvalidProductInfo => 'Érvénytelen termékinformáció',
            self::InvalidProductPrice => 'Érvénytelen termékár',
            self::InvalidVatValue => 'Érvénytelen ÁFA érték',
            self::InvalidQuantity => 'Érvénytelen mennyiség',
            self::InvalidProductVariant => 'Érvénytelen termékváltozat',
            self::InvalidProductGroup => 'Érvénytelen termékcsoport',
            self::InvalidPrice => 'Érvénytelen ár',
            self::MissingOrderRefField => 'A kereskedői tranzakcióazonosító hiányzik',
            self::InvalidDate => 'Érvénytelen dátum',
            self::InvalidDiscount => 'Érvénytelen kedvezmény',
            self::InvalidShippingAmount => 'Érvénytelen szállítási összeg',
            self::InvalidMethod => 'Érvénytelen módszer',
            self::InvalidRedirectUrl => 'Érvénytelen visszairányítási URL',
            self::MissingOrInvalidCustomerEmail => 'Email cím hiányzik, vagy nem email formátumú',
            self::InvalidLanguage => 'A tranzakció nyelve nem megfelelő',
            self::InvalidDiscountFormat => 'Érvénytelen kedvezmény formátum',
            self::InvalidShippingFormat => 'Érvénytelen szállítási formátum',
            self::InvalidOrMissingCurrency => 'A tranzakció pénzneme nem megfelelő, vagy hiányzik',
            self::InvalidTimeLimit => 'Érvénytelen időkorlát',
            self::InvalidWireTransferTimeLimit => 'Érvénytelen banki átutalási időkorlát',
            self::InvalidCommunicationState => 'Érvénytelen kommunikációs állapot',
            self::InvalidTimeoutSpec => 'Érvénytelen időtúllépés meghatározás',
            self::RefundLimitExceeded => 'Visszatérítési limit túllépve',
            self::RefundDeadlineExpired => 'Visszatérítési határidő lejárt',
            self::RefundNotAllowed => 'Visszatérítés nem engedélyezett',
            self::UserRedirectRequired => 'Felhasználó átirányítása szükséges',
            self::InvalidRequestSignature => 'Nem megfelelő aláírás a beérkező kérésben',
            self::InvalidRequestSignature2 => 'Nem megfelelő aláírás a beérkező kérésben',
            self::TimeoutFailedCall => 'Időtúllépés miatt sikertelen hívás',
            self::FailedTransactionSend => 'Sikertelen tranzakcióküldés az elfogadó felé',
            self::FailedTransactionCreation => 'Sikertelen tranzakciólétrehozás',
            self::CurrencyMismatch => 'A kérésben megadott devizanem nem egyezik a fiókhoz beállítottal',
            self::TwoStepNotEnabled => 'A kétlépcsős tranzakcióindítás nem engedélyezett a kereskedői fiókon',
            self::MissingInvoiceName => 'Számlázási adatokban a címzett hiányzik',
            self::MissingInvoiceCity => 'Számlázási adatokban a város kötelező',
            self::MissingInvoiceZip => 'Számlázási adatokban az irányítószám kötelező',
            self::MissingInvoiceAddress => 'Számlázási adatokban a cím első sora kötelező',
            self::MissingItemTitle => 'A termék neve kötelező',
            self::MissingItemPrice => 'A termék egységára kötelező',
            self::MissingItemQuantity => 'A rendelt mennyiség kötelező',
            self::MissingShippingName => 'Szállítási adatokban a címzett kötelező',
            self::MissingShippingCity => 'Szállítási adatokban a város kötelező',
            self::MissingShippingZip => 'Szállítási adatokban az irányítószám kötelező',
            self::MissingShippingAddress => 'Szállítási adatokban a cím első sora kötelező',
            self::MissingSdkVersion => 'Az sdkVersion kötelező',
            self::InvalidJsonFormat => 'Formátumhiba / érvénytelen JSON string',
            self::InvalidCountry => 'Érvénytelen ország',
            self::InvalidFinishAmount => 'Lezárás összege érvénytelen',
            self::ItemsOrTotalRequired => 'Termékek listája vagy tranzakcióföösszeg szükséges',
            self::InvalidUrl => 'Érvénytelen URL',
            self::MissingCardId => 'Hiányzó cardId',
            self::MaxOrderRefsExceeded => 'Lekérdezendő orderRef-ek maximális számának túllépése',
            self::MaxTransactionIdsExceeded => 'Lekérdezendő tranzakcióazonosítók maximális számának túllépése',
            self::QueryFromAfterUntil => 'Lekérdezésben a from az until időpontot meg kell előzze',
            self::QueryFromAndUntilRequired => 'Lekérdezésben from és until együttesen adandó meg',
            self::InvalidTransactionSource => 'Érvénytelen tranzakció forrás',
            self::TransactionIdAndTargetRequired => 'Tranzakcióazonosító és célpont szükséges',
            self::MissingTransactionId => 'Hiányzó tranzakcióazonosító',
            self::CardDataRequired => 'Bankkártya adatok szükségesek',
            self::CardBinRequired => 'Bankkártya BIN szükséges',
            self::AntiFraudHashRequired => 'Csalásellenes hash szükséges',
            self::DataSerializationError => 'Hiba összetett adat szöveges formába írásakor',
            self::AcquirerTransactionIdRequired => 'Acquirer tranzakcióazonosítója szükséges',
            self::QueryDateOrIdsRequired => 'Lekérdezéshez az indítás időszaka vagy azonosítók szükségesek',
            self::TransactionNotWalletBound => 'A tranzakció nem tárcához kötött',
            self::PartnerOptionRequired => 'Partner opció szükséges',
            self::PartnerAccountsRequired => 'Partner számlák szükségesek',
            self::InvalidTransactionStatus => 'Nem megfelelő tranzakcióstátusz',
            self::InvalidTransactionStatus2 => 'Nem megfelelő tranzakcióstátusz',
            self::VatAmountBelowZero => 'ÁFA összege kisebb, mint 0',
            self::InvalidTransactionMode => 'Érvénytelen tranzakciós mód',
            self::InvalidInstallmentPlan => 'Érvénytelen részletfizetés',
            self::JwtRequired => 'JWT szükséges',
            self::TransactionNotAllowedOnAccount => 'A tranzakció nem engedélyezett az elszámoló fiókon',
            self::InvalidEmailFormat => 'Érvénytelen email',
            self::InvalidDay => 'Érvénytelen nap',
            self::SimpleBusinessAccountError => 'Simple business fiók hiba / nem létező fiók',
            self::InvalidStartEndParams => 'Érvénytelen kezdő és záró paraméterek',
            self::InvalidDeviceId => 'Érvénytelen eszközazonosító',
            self::NotSoftPosAccount => 'Nem SoftPOS számla',
            self::InvalidTemplate => 'Érvénytelen sablon',
            self::InvalidOrderRefFormat => 'Érvénytelen rendelési hivatkozás',
            self::InvalidPeriod => 'Érvénytelen időszak',
            self::SoftPosNotAvailable => 'SoftPOS nem elérhető',
            self::RemoteAssignmentFailed => 'A tranzakció távoli hozzárendelése sikertelen',
            self::RemoteDeletionFailed => 'A tranzakció távoli törlése sikertelen',
            self::RemoteExpirationFailed => 'A tranzakció távoli lejáratának beállítása sikertelen',
            self::OriginalTransactionRequired => 'Eredeti tranzakció szükséges',
            self::InvalidAdditionalInfo => 'Érvénytelen további információ',
            self::PartnerIdRequired => 'Partner azonosító megadása kötelező',
            self::InvalidEamStatus => 'Érvénytelen EAM állapot',
            self::PaymentReferenceRequired => 'Fizetési hivatkozás megadása kötelező',
            self::DebtorBicRequired => 'Adós bankjának BIC kódja szükséges',
            self::EndToEndIdRequired => 'End-to-end azonosító megadása kötelező',
            self::InvalidItemPrice => 'Érvénytelen termékár',
            self::InvalidItemQuantity => 'Érvénytelen termékmennyiség',
            self::AmountPaidToMerchant => 'Összeg kifizetve a kereskedőnek',
            self::ApplePayNotEnabled => 'Apple Pay nem engedélyezett',
            self::EmailParamsRequired => 'E-mail paraméterek szükségesek',
            self::EmailTypeRequired => 'E-mail típus szükséges',
            self::CustomerEmailRequired => 'Ügyfél e-mail címe szükséges',
            self::InvalidSaltLength => 'Érvénytelen salt, nem 32-64 hosszú',
            self::TransactionBaseRequired => 'Tranzakció alapja szükséges',
            self::SimpleTransactionInPayment => 'Simple tranzakció a fizetés alatt',
            self::InvalidTransactionState => 'Érvénytelen tranzakció állapot',
            self::TransactionNotInCdeSession => 'A tranzakció nem CDE munkamenetben van',
            self::WireTransactionCreated => 'Létrejött utalási tranzakció',
            self::BrowserAcceptRequired => 'Böngésző accept kötelező',
            self::BrowserAgentRequired => 'Böngésző agent kötelező',
            self::BrowserIpRequired => 'Böngésző ip kötelező',
            self::BrowserJavaRequired => 'Böngésző java kötelező',
            self::BrowserLanguageRequired => 'Böngésző nyelv kötelező',
            self::BrowserColorRequired => 'Böngésző szín kötelező',
            self::BrowserHeightRequired => 'Böngésző magasság kötelező',
            self::BrowserWidthRequired => 'Böngésző szélesség kötelező',
            self::BrowserTzRequired => 'Böngésző tz kötelező',
            self::InvalidType => 'Érvénytelen type',
            self::RavenCallError => 'Hiba a Raven hívás során',
            self::InvalidIdentificationCode => 'Érvénytelen azonosító kód',
            self::InvalidMessage => 'Érvénytelen üzenet',
            self::InvalidTransactionSituation => 'Érvénytelen tranzakciós helyzet',
            self::InvalidRetailData => 'Érvénytelen kiskereskedelmi adatok',
            self::InvalidDevice => 'Érvénytelen eszköz',
            self::InvalidAccountId => 'Érvénytelen számlaazonosító',
            self::InvalidCustomerData => 'Érvénytelen ügyfél adatok',
            self::InvalidVerificationCode => 'Érvénytelen ellenőrző kód',
            self::MissingAuthCommunication => 'Hiányzó sikeres hitelesítési kommunikáció',
            self::RecommendationAlreadySent => 'Ajánlás már elküldve',
            self::MissingInstallmentData => 'Hiányzó részletfizetési adat',
            self::InvalidOptionIndex => 'Érvénytelen opció index',
            self::DomainSelectionNotAvailable => 'Tartomány választás nem elérhető',
            self::FullAmountPaymentNotAvailable => 'Teljes összegű fizetés nem elérhető',
            self::AcquiringCallError => 'Hiba az acquiring hívás során',
            self::InstallmentDataParseError => 'Részletfizetési adat értelmezési hiba',
            self::InvalidInstallmentNumber => 'Érvénytelen részletfizetési szám',
            self::MissingInstallmentOption => 'Hiányzó részletfizetési opció',
            self::MissingRecommendationCommunication => 'Hiányzó sikeres ajánlási kommunikáció',
            self::SettlementAccountIdRequired => 'Elszámolószámla-azonosító szükséges',
            self::SeriesSizeRequired => 'Sorozat méret szükséges',
            self::InvalidCardType => 'Érvénytelen kártyatípus',
            self::CardTransactionRejected => 'Kártya / tranzakció elutasítva',
            self::ApiV1Disabled => 'API v1 verziója le van tiltva',
            self::InvalidAppPlatform => 'Érvénytelen alkalmazás platform',
            self::InvalidTimestampApp => 'Érvénytelen időbélyeg',
            self::MobileAppNotFound => 'Mobil alkalmazás nem található',
            self::DeeplinkDataNotFound => 'Deeplink adatcsomag nem található',
            self::PlatformOrInternalIdsRequired => 'Platform vagy belső azonosítók szükségesek',
            self::ReturnUrlsRequired => 'Visszatérő URL-ek szükségesek',
            self::MultipleReturnUrls => 'Több visszatérő URL megadva',
            self::RtpNotEnabled => 'RTP nem engedélyezett',
            self::RtpInvalidBatchRef => 'Érvénytelen csomag hivatkozás',
            self::RtpInvalidOrderRef => 'Érvénytelen rendelési hivatkozás',
            self::RtpInvalidTotal => 'Érvénytelen teljes összeg',
            self::RtpInvalidCurrency => 'Érvénytelen pénznem',
            self::RtpCustomerRequired => 'Ügyfél szükséges',
            self::RtpEmailOrAccountRequired => 'Szükséges az ügyfél e-mail címe vagy bankszámlaszáma',
            self::RtpInvalidEmail => 'Érvénytelen ügyfél e-mail cím',
            self::RtpInvalidAccountNumber => 'Érvénytelen ügyfél bankszámlaszám',
            self::RtpInvalidRecurringTimes => 'Érvénytelen ismétlődő idők',
            self::RtpRecurringUntilRequired => 'Szükséges az ismétlődés időtartama',
            self::RtpRecurringUntilExceeded => 'Az ismétlődés időtartama túllépve',
            self::RtpInvalidRecurringDay => 'Érvénytelen ismétlődő nap',
            self::RtpInvalidRecurringInterval => 'Érvénytelen ismétlődő intervallum',
            self::RtpEmptyPayments => 'Üres fizetések',
            self::RtpInvalidPaymentResult => 'Érvénytelen fizetési eredmény',
            self::RtpInvalidMerchant => 'Érvénytelen kereskedő',
            self::RtpSdkVersionRequired => 'Szükséges az SDK verziója',
            self::RtpTransactionAlreadyExists => 'A tranzakció már létezik',
            self::RtpInvalidLanguage => 'Érvénytelen nyelv',
            self::RtpInvalidTransactionState => 'Érvénytelen tranzakciós állapot',
            self::RtpInvalidBatchOrOrderRef => 'Érvénytelen csomag vagy rendelési hivatkozás',
            self::RtpInvalidQueryParams => 'Érvénytelen lekérdezési paraméterek',
            self::RtpOrderIdSizeExceeded => 'Rendelési azonosító méret túllépés',
            self::RtpFromAfterUntil => 'A kezdő dátum a záró dátum után van',
            self::RtpFromAndUntilRequired => 'Kezdő és záró dátum együtt szükséges',
            self::RtpMissingRtpId => 'Hiányzó RTP azonosító',
            self::RtpInvalidState => 'Érvénytelen állapot',
            self::RtpInvalidDeadline => 'Érvénytelen határidő',
            self::RtpOrderRefOrTransactionIdRequired => 'Lekérdezéshez rendelési hivatkozás vagy tranzakcióazonosító szükséges',
            self::RtpGiroError => 'Giro hiba',
            self::RtpTransactionNotFound => 'A tranzakció nem létezik',
            self::RtpCustomerOrAccountRequired => 'Ügyfél vagy bankszámla szükséges',
            self::RtpCommentTooLong => 'Túl hosszú közlemény',
            self::RtpAccountAlreadySet => 'A bankszámla már be van állítva',
            self::RtpTransactionCountExceeded => 'Tranzakciók számának túllépése',
            self::RtpEmptyPaymentAmount => 'Üres fizetendő összeg RTP-nél',
            self::RtpTransactionInit => 'Tranzakció inicializálása',
            self::RtpWaitingForAccountData => 'Várakozás a bankszámla adatokra',
            self::RtpReadyToSend => 'A tranzakció elküldésre kész',
            self::RtpTransactionSent => 'A tranzakció elküldve',
            self::RtpTransactionReceived => 'A tranzakció fogadva',
            self::RtpTransactionAccepted => 'A tranzakció elfogadva',
            self::RtpTransactionRejected => 'A tranzakció elutasítva',
            self::RtpTransactionExpired => 'A tranzakció lejárt',
            self::RtpTransactionReversed => 'A tranzakció visszafordítva',
            self::RtpTransactionFailed => 'Sikertelen tranzakció',
            self::RtpTransactionImmutable => 'Változtathatatlan tranzakció',
            self::RtpTransactionPaid => 'Fizetett tranzakció',
            self::RtpTransactionNotFound2 => 'Tranzakció nem található',
            self::RtpTransactionFinalState => 'Tranzakció végállapotban',
            self::RtpInvalidPartnerAccount => 'Érvénytelen partner bankszámla',
            self::RtpReversalInProgress => 'Visszafordítás folyamatban',
            self::RtpTransactionsRequired => 'Tranzakciók szükségesek',
            self::RtpGeneralError => 'Általános RTP hiba',
            self::SettlementMerchantNotFound => 'A kereskedő nem található',
            self::SettlementGeneralError => 'Általános hiba',
        };
    }
}
